good_night:
  alias: Good Night!
  sequence:
  - service: remote.send_command
    data:
      command: PowerOff
      num_repeats: 2
      hold_secs: 0.5
    target:
      entity_id: remote.sony_xbr_65a8h
  - scene: scene.relax
  - scene: scene.living_room_off
  mode: single
  icon: mdi:weather-night
