services:
  fail2banInit:
    image: busybox:latest
    container_name: init
    network_mode: none
    volumes:
      - /var/run:/var/run
    command:
      - sh
      - -c
      - mkdir -p /var/run/fail2ban || exit 0
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    depends_on:
      - fail2banInit
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "fail2ban-client ping || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /volume1/docker/fail2ban/config:/config
      - /var/run/fail2ban:/var/run/fail2ban
      - /var/log:/var/log:ro
      - /var/log/nginx:/remotelogs/nginx:ro
    restart: always
    labels:
      - "diun.enable=true"
  fail2ban_exporter:
    image: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter:latest
    container_name: fail2ban_exporter
    restart: always
    depends_on:
      - fail2ban
    networks:
      - fail2ban
    volumes:
      - /var/run/fail2ban:/var/run/fail2ban:ro
    ports:
      - '9191:9191'
    labels:
      - "diun.enable=true"

networks:
  fail2ban:
