services:
  wealthfolio:
    ports:
      - '8088:8088'
    container_name: wealthfolio
    image: ghcr.io/wealthfolio/wealthfolio:3.7.0@sha256:1f158231e97f2b8804908091631b5aeedf8d4b4254110e6be997133047a3a600 
    env_file: .env
    environment:
      WF_DB_PATH: /data/wealthfolio.db
      WF_LISTEN_ADDR: 0.0.0.0:8088
      WF_CORS_ALLOW_ORIGINS: http://localhost:8088,https://wealthfolio.tailc6343.ts.net
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O/dev/null localhost:8088/api/v1/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./data:/data
    restart: always
