services:
  wealthfolio:
    ports:
      - '8088:8088'
    container_name: wealthfolio
    image: ghcr.io/wealthfolio/wealthfolio:3.9.1@sha256:19d287c27a8985aeee0bba84d658920e1e964b0ebce19f98b69996d40b3abcb4 
    env_file: .env
    environment:
      WF_DB_PATH: /data/wealthfolio.db
      WF_LISTEN_ADDR: 0.0.0.0:8088
      WF_CORS_ALLOW_ORIGINS: http://localhost:8088,https://wealthfolio.tailc6343.ts.net
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O/dev/null localhost:8088/api/v1/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./data:/data
    restart: always
