groups:
    - name: MySQLdAlerts
      rules:
        - alert: MySQLDown
          annotations:
            description: MySQL {{$labels.job}} on {{$labels.instance}} is not up.
            summary: MySQL not up.
          expr: mysql_up != 1
          for: 5m
          labels:
            severity: critical
