global: {}

#http_config:
#  proxy_url: https://alerts.home.lan

route:
  receiver: email

receivers:
 - name: 'discord'
   discord_configs:
     webhook_url_file: /var/run/secrets/discord_webhook.txt
  - name: 'ntfy'
    webhook_configs:
      - url: https://ntfy.home.lan/alertmanager
  - name: email
    email_configs:
      - send_resolved: true
        to: janikgar@gmail.com
        from: janikgar@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: janikgar@gmail.com
        auth_password_file: /var/run/secrets/email_token.txt
