modules:
  remote_dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "www.google.com"
      query_type: "A"
  local_dns:
    prober: dns
    timeout: 5s
    dns:
      query_name: "certs.home.lan"
      query_type: "CNAME"
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: ip4
