auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

querier:
  max_concurrent: 2048

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2024-10-11
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h
 
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 4096

pattern_ingester:
  enabled: true

limits_config:
  allow_structured_metadata: false
  volume_enabled: true
  retention_period: 14d
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_query_series: 10000

compactor:
  working_directory: /loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 24h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
