server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"
  
positions:
    filename: /tmp/positions.yaml
  
clients:
    - url: http://loki:3100/loki/api/v1/push
  
scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: syslog
  - job_name: docker
    pipeline_stages:
    - json:
        expressions:
          container: "attrs.tag"
        output: log
        stream: stream
        timestamp: time
        container: container
    - labels:
        stream:
        container:
    - timestamp:
        source: timestamp
        format: RFC3339Nano
    - output:
        source: output
    static_configs:
    - targets:
      - localhost
      labels:
        job: docker
        __path__: /var/docker/**/*log
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varstarlogs
        __path__: /var/log/**/*log
