volumes:
  surmai_data:

services:
  surmai:
    container_name: surmai
    # latest images point to released versions
    # For the yet unreleased updates, use the main tag i.e.
    # image: ghcr.io/rohitkumbhar/surmai:main
    image: ghcr.io/rohitkumbhar/surmai:v0.5.5@sha256:d9e7f3158cd03d9f6e3bcef5b3589a3708227f61895bc7e1fc5fb8e4f166873e
    volumes:
      - ./surmai_data:/pb_data
    ports:
      - "9090:8080"
    restart: always
    env_file: .env
    environment:
      PB_DATA_DIRECTORY: /pb_data