volumes:
  surmai_data:

services:
  surmai:
    container_name: surmai
    # latest images point to released versions
    # For the yet unreleased updates, use the main tag i.e.
    # image: ghcr.io/rohitkumbhar/surmai:main
    image: ghcr.io/rohitkumbhar/surmai:v0.5.6@sha256:176639fc91829370c469dae78038811f8672663424500b21fd6bcb2a66659359
    volumes:
      - ./surmai_data:/pb_data
    ports:
      - "9090:8080"
    restart: always
    env_file: .env
    environment:
      PB_DATA_DIRECTORY: /pb_data