services:
  minio:
    ports:
      - '30900:9000'
      - '30901:9001'
    volumes:
      - ./data:/data
      - ./config.txt:/etc/silo/config.env:ro
      - ./secret_root_user.txt:/var/run/secrets/root_user.txt:ro
      - ./secret_root_password.txt:/var/run/secrets/root_password.txt:ro
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/silo/config.env
      MINIO_ROOT_USER_FILE: /var/run/secrets/root_user.txt
      MINIO_ROOT_PASSWORD_FILE: /var/run/secrets/root_password.txt
    container_name: silo
    image: pgsty/silo:RELEASE.2026-08-06T00-00-00Z-distroless@sha256:58b5aaa8ab94f82b1ed85c4c351594adbd01c6f0628380f5a85abf1e9216b80a
    command: server --console-address :9001
    user: "1032:100"
    networks:
      - silo
    restart: always
    healthcheck:
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    
networks:
  silo:
