services:
  wf_converter:
    ports:
      - '8000:8000'
    container_name: wf_converter
    image: ghcr.io/janikgar/wealthfolio_converter:v0.0.3@sha256:a12509b9034bc878d1b29eed0190c5621d7b4c3d6ee5a82a1a10b2fae27b2612
    env_file: .env
    environment:
      STAGE: PRODUCTION
    restart: always
