services:
  wf_converter:
    ports:
      - '8000:8000'
    container_name: wf_converter
    image: ghcr.io/janikgar/wealthfolio_converter:sha-7d05ed0@sha256:4cd35a3c31903da1d4d314f58936f87c8363747996f0e21a323be55f0e93a403
    env_file: .env
    environment:
      STAGE: PRODUCTION
    restart: always
