services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest@sha256:243a9d012d27996ed933a590c9ffb690c4dcf4e436d786d3680805fef3b26ee6
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: none
