services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest@sha256:5cfad03f595396eb81ae3ff25e592b919602697ae6b423c090031d1648ad5300
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: none
