services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest@sha256:9b297ab38e8472ac333dc6133ff46e52f1e8ffb45cc86664242fb324613c2294
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: none
