services:
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest@sha256:3aa672c8d4263d9b0a0f45364ee810a6d70f36af237585b2c5d9b29a33a91db4
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: none
